# Generated by Django 3.1.4 on 2021-01-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_auto_20210116_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('planes', models.ManyToManyField(related_name='passengers', to='airline.flights')),
            ],
        ),
    ]
